#!/usr/bin/env python3
"""
gen_square_lattice

Makes a rho = 1 square lattice

Usage:
    gen_square_lattice lin_rep > outfile

Flags:
    --help -> print this message
"""
import sys

if __name__ == "__main__":
    if "--help" in sys.argv:
        print(__doc__)
        sys.exit(0)

    lin_rep = int(sys.argv[1])

    print(2)
    print("{} 0.0 0.0 0.0".format(float(lin_rep)))
    print("0.0 {} 0.0 0.0".format(float(lin_rep)))
    
    for i in range(lin_rep):
        for j in range(lin_rep):
            print("{} {} 0.0 0.0".format(float(i), float(j)))

