#!/usr/bin/env python3
"""
sample_hp.py
Author: Timothy Middlemas

Script to sample H_P(r) by binning nearest neighbors

Uses Scipy's cKDTree implementation for lookup

Implements periodic boundary conditions by 1 layer of
replication. Note that this is usually, but not always
correct, so be careful.

Usage: python3 sample_hp.py [cutoff] [n_bins] [infiles ...] > [outfile]

Will interpret multiple infiles as ensemble average

Options:
    --help -> Print this message
"""

import sys
import numpy as np
from scipy.spatial import cKDTree

if __name__ == "__main__":
    if "--help" in sys.argv:
        print(__doc__)
        sys.exit()

    cutoff = float(sys.argv[1])
    n_bins = int(sys.argv[2])
    n_files = len(sys.argv[3:])

    step = cutoff/float(n_bins)
    check = np.linspace(0.0, cutoff, num=n_bins+1)
    check_upper = check[1:]
    check_lower = check[:-1]
    domain = check_upper - step/2.0
    hp = np.zeros(n_bins)

    for fname in sys.argv[3:]:
        # Read necessary stuff from file
        infile = open(fname)
        dim = int(infile.readline())
        basis = np.loadtxt(infile, max_rows=dim)[:, :dim]
        # https://stackoverflow.com/questions/31698242/python-how-can-i-force-1-element-numpy-arrays-to-be-two-dimensional
        points = np.atleast_2d(np.loadtxt(infile))[:, :dim]
        n_points = len(points)

        # Construct periodic images, tree, and samples
        periodic = np.tile(points, (3**dim, 1))
        for i in range(3**dim):
            for j in range(dim):
                a = i
                for k in range(j):
                    a = a//3
                a = (a%3) - 1
                periodic[i*n_points:(i+1)*n_points, :] += a*basis[j, :]
        
        tree = cKDTree(periodic)
        samples = points
        # print(points)

        # Bin samples
        dd, ii = tree.query(samples, k=2, n_jobs=-1)
        check_m_upper = np.tile(check_upper, (n_points, 1))
        check_m_lower = np.tile(check_lower, (n_points, 1))
        # print(check_m_upper)
        # https://stackoverflow.com/questions/17428621/python-differentiating-between-row-and-column-vectors
        bin_m_upper = np.less(dd[:, 1, np.newaxis], check_m_upper, dtype=float)
        bin_m_lower = np.greater_equal(dd[:, 1, np.newaxis], check_m_lower, dtype=float)
        hp += np.sum(bin_m_lower*bin_m_upper, axis=0)

    # Normalize
    hp /= float(n_points*n_files)*step
    
    count = np.full(n_bins, float(n_points*n_files))
    
    np.savetxt(sys.stdout.buffer, np.stack([domain, hp, count], -1))
